 COPY items(id, uid, domain, cn, department, title, who, logon_count,num_logons7,num_share7,num_file7,num_ad7,
 num_n7,
 num_logons14,
 num_share14,
 num_file14,
 num_ad14,
 num_n14,
 num_logons30,
 num_share30,
 num_file30,
 num_ad30,
 num_n30,
 num_logons150,
 num_share150,
 num_file150,
 num_ad150,
 num_n150,
 num_logons365,
 num_share365,
 num_file365,
 num_ad365,
 num_n365,
 has_user_principal_name,
 has_mail,
 has_phone,
 flag_disabled,
 flag_lockout,
 flag_password_not_required,
flag_password_cant_change,
 flag_dont_expire_password,
 owned_files,
 num_mailboxes,
 num_member_of_groups,
 num_member_of_indirect_groups,
member_of_indirect_groups_ids,
 member_of_groups_ids,
is_admin,
is_service) FROM 'D:\docs\file_with_data.csv'
DELIMITER ','
CSV HEADER;
